version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "contract-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ksuersre5r56"
s3_prefix = "contract-service"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
